CREATE TABLE addresses(
	addr_id SERIAL NOT NULL PRIMARY KEY,
	country VARCHAR(64) NOT NULL,
	city VARCHAR(255) NOT NULL,
	street VARCHAR(255) NOT NULL,
	house VARCHAR(10) NOT NULL,
	flat VARCHAR(10) NOT NULL
);
